name: CI/CD Pipeline to GCP Artifact Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  # Your GCP service account key stored in GitHub secrets

      # Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # GCP project ID stored in GitHub secrets

      # Step 4: Authenticate Docker to use Google Artifact Registry (GAR)
      - name: Authenticate Docker with GAR
        run: gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/personal-gpt-gemini-toolkit/toolkit:v1.0 \
          --build-arg gemini_key=${{ secrets.OPENAI_API_KEY }} \
          --build-arg PERSONAL_ACCESS_TOKEN_GITHUB=${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }} .

      # Step 6: Push the Docker image to Google Artifact Registry (GAR)
      - name: Push Docker image to GAR
        run: |
          docker push us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/personal-gpt-gemini-toolkit/toolkit:v1.0

      # Optional Step 7: Deploy the Docker image to Google Cloud Run (commented out)
      # - name: Deploy to Google Cloud Run
      #   run: |
      #     gcloud run deploy personal-gpt-gemini-toolkit \
      #       --image us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/personal-gpt-gemini-toolkit/toolkit:v1.0 \
      #       --platform managed \
      #       --region us-east1 \
      #       --allow-unauthenticated \
      #       --update-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
