name: Backend Test Workflow

# Trigger the workflow on push to the dev branch and manual dispatch
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment for running test.py
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      # Step 3: Install Python dependencies for FastAPI (if needed)
      - name: Install dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r ../requirements.txt

      # Step 4: Build and run the backend in a Docker container
      - name: Build and run Docker container for backend
        run: |
          docker build -t my-fastapi-backend -f Dockerfile .
          docker run -d -p 8000:8000 my-fastapi-backend

      # Step 5: Wait for the backend to start up
      - name: Wait for backend to be ready
        run: sleep 10

      # Step 6: Run test.py to check if the backend is working
      - name: Run Backend Health Check
        run: |
          cd backend
          python test.py

      # Step 7: Clean up Docker containers
      - name: Clean up
        run: docker stop $(docker ps -q) && docker rm $(docker ps -a -q)

      # Step 8: Merge dev into main if tests pass
      - name: Merge dev into main
        if: success()  # Only run this step if the previous steps were successful
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git merge dev
          git push origin main
